### ISSUE TITLE
Logo of tools

### ISSUE THREAD

**Issue by tarunmangukiya** [LisaDziuba/Awesome-Design-Tools#264]
Hi Team,

Thanks for curating the list. I have this little suggestion on listing. How about having a logo of that plugin on the site?

Current site will look more useful to users if we add logos.
![image](https://user-images.githubusercontent.com/12470086/67652699-1f64e180-f96c-11e9-844a-234d348ecf05.png)

I think we can easily fetch logos in case of sketch plugin and can figure out more ways for other plugins!

**Comment by berezovskycom** [comment]
Hi @tarunmangukiya! Thanks for your idea!
Any thoughts on how can it be implemented?
When we were developing Awesome Design Tools websites' repo, we chose a priority of faster page load against logos, because they do take time for user to view the page, and, as you might have noticed, we have so many tools that creating such feature would take a lot of time.
But, surely, it would be better to have tools' logos, not only for the creators, but users itself.
I got your idea on my backlog. Thanks!

**Comment by tarunmangukiya** [comment]
Yes.
Sketch: Every sketch plugin does have the `manifest.json` file with `icon` key in that. So we can easily get icons for Sketch Plugins.
XD, it'll be bit complex task, but it is possible.

**Comment by tarunmangukiya** [comment]
For faster page loading we can use `<img loading="lazy" src="..." />`. This will keep page faster and give better experience to users.

**Comment by Yi98** [comment]
Hi! May I know how to run the application on my local machine? I would like to try to implement this feature.
